condition_encoder_config:
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
cylinder_encoder_config:
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
drive_encoder_config:
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
fuel_encoder_config:
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
manufacturer_encoder_config:
  use_grouping: true
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
paint_color_encoder_config:
  use_grouping: true
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
state_encoder_config:
  use_grouping: true
  use_top_tier_flag: true
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
transmission_encoder_config:
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
type_encoder_config:
  use_grouping: true
  use_label_encoding: true
  use_target_encoding: true
  target_encoder_config:
    smoothing: 0.037699689079676454
    min_samples_leaf: 2
    noise_level: 0.1058799309100469
year_encoder_config:
  use_1987_flag: true
  use_1975_flag: true
price_upper_bound: 60000.0
price_lower_bound: 0.0
remove_outliers_val: false
